version: '3'
services:
  server:
    image: my-app-server:1.0
    ports:
      - 5000:5000
    environment:
      - MONGO_URL=${MONGO_URL}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
  client:
    image: my-app-client:1.0
    ports:
      - 3000:3000
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${DB_SERVER}
volumes:
  mongo-data:
    driver: local
